services:
  front-app:
    image: node:20-alpine
    container_name: react-dev-env
    working_dir: /app
    # Mantenemos el proceso vivo y ejecutamos el servidor de desarrollo
    command: sh -c "npm install && npm run dev"
    ports:
      - "5173:5173" # Mapeo del puerto de Vite
    volumes:
      # Este es el volumen principal: sincroniza nuestra carpeta con /app del contenedor
      - ./:/app
      # Volumen anónimo: Evitamos sincronizar node_modules para no romper los binarios de Linux
      - /app/node_modules

      
